apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- if .Values.storage.books.annotations }}
  annotations:
    {{ toYaml .Values.storage.books.annotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "calibre-web.labels" . | nindent 4 }}
  name: {{ template "calibre-web.fullname" . }}-books
spec:
  accessModes:
    {{ toYaml .Values.storage.books.accessModes | indent 4 }}
  storageClassName: {{ .Values.storage.books.storageClassName }}
  resources:
    requests:
      storage: "{{ .Values.storage.books.size }}"

