apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "radicale.fullname" . }}
  labels:
    {{- include "radicale.labels" . | nindent 4 }}
data:
  config.cfg: |
    [server]
    hosts = 0.0.0.0:5232

    [storage]
    filesystem_folder = /data/collections
