apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- if .Values.storage.annotations }}
  annotations:
    {{ toYaml .Values.storage.annotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "radicale.labels" . | nindent 4 }}
  name: {{ template "radicale.fullname" . }}
spec:
  accessModes:
    {{ toYaml .Values.storage.accessModes | indent 4 }}
  storageClassName: {{ .Values.storage.storageClassName }}
  resources:
    requests:
      storage: "{{ .Values.storage.size }}"

